echo "\nBegining script"
EXEC=./translator
ROOT_DIR=../examples/Virtual

MEMORY_ACCESS=MemoryAccess
BASIC=BasicTest
POINTER=PointerTest
STATIC=StaticTest

STACK_ARITHMETIC=StackArithmetic
SIMPLE_ADD=SimpleAdd
STACK_TEST=StackTest

BASIC_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$BASIC/$BASIC.vm
BASIC_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$BASIC/$BASIC.asm
POINTER_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$POINTER/$POINTER.vm
POINTER_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$POINTER/$POINTER.asm
STATIC_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$STATIC/$STATIC.vm
STATIC_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$STATIC/$STATIC.asm
SIMPLE_ADD_INPUT=$ROOT_DIR/$STACK_ARITHMETIC/$SIMPLE_ADD/$SIMPLE_ADD.vm
SIMPLE_ADD_OUTPUT=$ROOT_DIR/$STACK_ARITHMETIC/$SIMPLE_ADD/$SIMPLE_ADD.asm
STACK_TEST_INPUT=$ROOT_DIR/$STACK_ARITHMETIC/$STACK_TEST/$STACK_TEST.vm
STACK_TEST_OUTPUT=$ROOT_DIR/$STACK_ARITHMETIC/$STACK_TEST/$STACK_TEST.asm




echo "\nCompiling executable\n"
make

echo "\nTesting Basic\n"
$EXEC $BASIC_INPUT $BASIC_OUTPUT
echo "\nTesting Pointer\n"
$EXEC $POINTER_INPUT $POINTER_OUTPUT
echo "\nTesting INPUT\n"
$EXEC $STATIC_INPUT $STATIC_OUTPUT
echo "\nTesting Simple Add\n"
$EXEC $SIMPLE_ADD_INPUT $SIMPLE_ADD_OUTPUT
echo "\nTesting StackTest\n"
$EXEC $STACK_TEST_INPUT $STACK_TEST_OUTPUT


echo "Script end"