echo "\nBegining script"
EXEC=./translator
ROOT_DIR=../examples/Virtual
MEMORY_ACCESS=MemoryAccess
BASIC=BasicTest
POINTER=PointerTest
STATIC=StaticTest

BASIC_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$BASIC/$BASIC.vm
BASIC_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$BASIC/$BASIC.asm
POINTER_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$POINTER/$POINTER.vm
POINTER_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$POINTER/$POINTER.asm
STATIC_INPUT=$ROOT_DIR/$MEMORY_ACCESS/$STATIC/$STATIC.vm
STATIC_OUTPUT=$ROOT_DIR/$MEMORY_ACCESS/$STATIC/$STATIC.asm

echo "\nCompiling executable\n"
make

echo "\nTesting Basic\n"
$EXEC $BASIC_INPUT $BASIC_OUTPUT
echo "\nTesting Pointer\n"
$EXEC $POINTER_INPUT $POINTER_OUTPUT
echo "\nTesting INPUT\n"
$EXEC $STATIC_INPUT $STATIC_OUTPUT

echo "Script end"