export const TokenConstants = {
    KEYWORD: 'keyword',
    SYMBOL: 'symbol', 
    INTEGER: 'integer',
    STRING: 'string',
    IDENTIFIER: 'identifier'
}

export const NodeConstants = {
    KEYWORD: TokenConstants.KEYWORD,
    SYMBOL: TokenConstants.SYMBOL,
    INTEGER: TokenConstants.INTEGER,
    STRING: TokenConstants.STRING,
    IDENTIFIER: TokenConstants.IDENTIFIER, 
    CLASS: 'class',
    CLASSVARDEC: 'classVarDec',
    TYPE: 'type',
    SUBROUTINEDEC: 'subroutineDec',
    PARAMETERLIST: 'parameterList',
    SUBROUTINEBODY: 'subroutineBody',
    VARDEC: 'varDec',
    CLASSNAME: 'className',
    SUBROUTINENAME: 'subroutineName',
    VARNAME: 'varName',
    STATEMENTS: 'statements',
    STATEMENT: 'statement',
    LETSTATEMENT: 'letStatement',
    IFSTATEMENT: 'ifStatement',
    WHILESTATEMENT: 'whileStatement',
    DOSTATEMENT: 'doStatement',
    RETURNSTATEMENT: 'returnStatement',
    EXPRESSION: 'expression',
    TERM: 'term',
    SUBROUTINECALL: 'subroutineCall',
    EXPRESSIONLIST: 'expressionList',
    OP: 'op',
    UNARYOP: 'unaryOp',
    KEYWORDCONSTANT: 'keywordConstant'
}

export const Keywords = {
    "class": true,
    "constructor": true,
    "function": true,
    "method": true,
    "field": true,
    "static": true,
    "var": true,
    "int": true,
    "char": true,
    "boolean": true,
    "void": true,
    "true": true,
    "false": true,
    "null": true,
    "this": true,
    "let": true,
    "do": true,
    "if": true,
    "else": true,
    "while": true,
    "return": true
}

export const Symbols = {
    '{': true,
    '}': true,
    '(': true,
    ')': true,
    '[': true,
    ']': true,
    '.': true,
    ',': true,
    ';': true,
    '+': true,
    '-': true,
    '*': true,
    '/': true,
    '&': true,
    '|': true,
    '<': true,
    '>': true,
    '=': true,
    '~': true,
}